expressway_mapping = {
    "KPE": {
        "1001": "View from KPE/ECP",
        "1002": "View from Kallang Bahru",
        "1003": "View from KPE/PIE",
        "1004": "View from Kallang Way Flyover",
        "1005": "View from Defu Flyover",
        "1006": "View from Tampines Flyover",
    },
    "MCE": {
        "1501": "View from Maxwell Road",
        "1502": "View from Marina Boulevard/Marina Coastal Drive",
        "1503": "View from MCE 1.02km",
        "1504": "View from MCE/ECP",
        "1505": "View from Marina Boulevard",
    },
    "Loyang Ave / Tanah Merah Coast Road": {
        "1111": "View from TPE(PIE), Exit 2 to Loyang Ave",
        "1112": "View from TPE(PIE), Tampines Viaduct",
        "1113": "View from Tanah Merah Coast Road towards Changi",
    },
    "CTE": {
        "1701": "View from Moulmein Flyover",
        "1702": "View from Braddell Flyover",
        "1703": "View from St George Road",
        "1704": "View from Entrance from Chin Swee Road",
        "1705": "View from Ang Mo Kio Ave 5 Flyover",
        "1706": "View from Yio Chu Kang Flyover",
        "1707": "View from Bukit Merah Flyover",
        "1709": "View from Exit 6 to Bukit Timah Road",
        "1711": "View from Ang Mo Kio Ave 1 Flyover",
    },
    "Woodlands Checkpoint": {
        "2701": "View from Woodlands Causeway (Towards Johor)",
        "2702": "View from Woodlands Checkpoint (Towards BKE)",
    },
    "BKE": {
        "2703": "View from Chantek Flyover",
        "2704": "View from Woodlands Flyover (Towards Checkpoint)",
        "2705": "View from Dairy Farm Flyover",
        "2706": "View from after KJE Exit",
        "2707": "View from Mandai Rd Entrance",
        "2708": "View from Exit 5 to KJE (Towards Checkpoint)",
    },
    "ECP": {
        "3702": "View from Entrance from PIE",
        "3704": "View from Entrance from MCE",
        "3705": "View from Exit 2A to Changi Coast Road",
        "3793": "View from Laguna Flyover",
        "3795": "View from Marine Parade Flyover",
        "3796": "View from Tanjong Katong Flyover",
        "3797": "View from Tanjong Rhu",
        "3798": "View from Benjamin Sheares Bridge",
    },
    "Tuas Checkpoint": {
        "4703": "View from Second Link at Tuas",
        "4713": "View from Tuas Checkpoint",
    },
    "AYE": {
        "4701": "View from Towards Alexandra Road",
        "4702": "View from Keppel Viaduct",
        "4704": "View from Lower Delta Road",
        "4705": "View from Entrance from Yuan Ching Rd",
        "4706": "View from Near NUS",
        "4707": "View from Entrance from Jln Ahmad Ibrahim",
        "4708": "View from Near Dover Drive",
        "4710": "View from Towards Pandan Gardens",
        "4712": "View from After Tuas West Road",
        "4714": "View from Near West Coast Walk",
        "4716": "View from Entrance from Benoi Rd",
    },
    "Sentosa Gateway": {
        "4798": "View from Sentosa Gateway (Towards Telok Blangah)",
        "4799": "View from Sentosa Gateway (Towards Sentosa)",
    },
    "PIE": {
        "5794": "View from Bedok North",
        "5795": "View from Eunos Flyover",
        "5797": "View from Paya Lebar Flyover",
        "5798": "View from Kallang Way",
        "5799": "View from Woodsville Flyover",
        "6701": "View from Kim Keat Link",
        "6703": "View from Thomson Flyover",
        "6704": "View from Mount Pleasant",
        "6705": "View from Adam Road",
        "6706": "View from Bukit Timah Expressway",
        "6708": "View from Nanyang Flyover",
        "6710": "View from Entrance from Jalan Anak Bukit",
        "6711": "View from Entrance to PIE from ECP Changi",
        "6712": "View from Exit 27 to Clementi Ave 6",
        "6713": "View from Entrance from Simei Ave",
        "6714": "View from Exit 35 to KJE",
        "6715": "View from Hong Kah Flyover",
        "6716": "View from Tuas Flyover",
    },
    "TPE": {
        "7791": "View from Upp Changi Flyover Towards PIE",
        "7793": "View from Tampines Ave 10 Entrance",
        "7794": "View from TPE(KPE) Exit",
        "7795": "View from Entrance To Tampines Flyover",
        "7796": "View from Exit to Punggol Flyover",
        "7797": "View from Seletar West Link",
        "7798": "View from Seletar Flyover",
    },
    "KJE": {
        "8701": "View from Choa Chu Kang West Flyover",
        "8702": "View from Exit To BKE",
        "8704": "View from Entrance From Choa Chu Kang Dr",
        "8706": "View from Tengah Flyover",
    },
    "SLE": {
        "9701": "View from Lentor Flyover",
        "9702": "View from Upp Thomson Flyover",
        "9703": "View from SLE(BKE) Exit",
        "9704": "View from Ulu Sembawang Flyover",
        "9705": "View from Marsiling Flyover",
        "9706": "View from Mandai Flyover",
    },
}

updated_expressway_mapping = {
    "1001": ("KPE", "View from KPE/ECP"),
    "1002": ("KPE", "View from Kallang Bahru"),
    "1003": ("KPE", "View from KPE/PIE"),
    "1004": ("KPE", "View from Kallang Way Flyover"),
    "1005": ("KPE", "View from Defu Flyover"),
    "1006": ("KPE", "View from Tampines Flyover"),
    "1501": ("MCE", "View from Maxwell Road"),
    "1502": ("MCE", "View from Marina Boulevard/Marina Coastal Drive"),
    "1503": ("MCE", "View from MCE 1.02km"),
    "1504": ("MCE", "View from MCE/ECP"),
    "1505": ("MCE", "View from Marina Boulevard"),
    "1111": (
        "Loyang Ave / Tanah Merah Coast Road",
        "View from TPE(PIE), Exit 2 to Loyang Ave",
    ),
    "1112": (
        "Loyang Ave / Tanah Merah Coast Road",
        "View from TPE(PIE), Tampines Viaduct",
    ),
    "1113": (
        "Loyang Ave / Tanah Merah Coast Road",
        "View from Tanah Merah Coast Road towards Changi",
    ),
    "1701": ("CTE", "View from Moulmein Flyover"),
    "1702": ("CTE", "View from Braddell Flyover"),
    "1703": ("CTE", "View from St George Road"),
    "1704": ("CTE", "View from Entrance from Chin Swee Road"),
    "1705": ("CTE", "View from Ang Mo Kio Ave 5 Flyover"),
    "1706": ("CTE", "View from Yio Chu Kang Flyover"),
    "1707": ("CTE", "View from Bukit Merah Flyover"),
    "1709": ("CTE", "View from Exit 6 to Bukit Timah Road"),
    "1711": ("CTE", "View from Ang Mo Kio Ave 1 Flyover"),
    "2701": ("Woodlands Checkpoint", "View from Woodlands Causeway (Towards Johor)"),
    "2702": ("Woodlands Checkpoint", "View from Woodlands Checkpoint (Towards BKE)"),
    "2703": ("BKE", "View from Chantek Flyover"),
    "2704": ("BKE", "View from Woodlands Flyover (Towards Checkpoint)"),
    "2705": ("BKE", "View from Dairy Farm Flyover"),
    "2706": ("BKE", "View from after KJE Exit"),
    "2707": ("BKE", "View from Mandai Rd Entrance"),
    "2708": ("BKE", "View from Exit 5 to KJE (Towards Checkpoint)"),
    "3702": ("ECP", "View from Entrance from PIE"),
    "3704": ("ECP", "View from Entrance from MCE"),
    "3705": ("ECP", "View from Exit 2A to Changi Coast Road"),
    "3793": ("ECP", "View from Laguna Flyover"),
    "3795": ("ECP", "View from Marine Parade Flyover"),
    "3796": ("ECP", "View from Tanjong Katong Flyover"),
    "3797": ("ECP", "View from Tanjong Rhu"),
    "3798": ("ECP", "View from Benjamin Sheares Bridge"),
    "4703": ("Tuas Checkpoint", "View from Second Link at Tuas"),
    "4713": ("Tuas Checkpoint", "View from Tuas Checkpoint"),
    "4701": ("AYE", "View from Towards Alexandra Road"),
    "4702": ("AYE", "View from Keppel Viaduct"),
    "4704": ("AYE", "View from Lower Delta Road"),
    "4705": ("AYE", "View from Entrance from Yuan Ching Rd"),
    "4706": ("AYE", "View from Near NUS"),
    "4707": ("AYE", "View from Entrance from Jln Ahmad Ibrahim"),
    "4708": ("AYE", "View from Near Dover Drive"),
    "4710": ("AYE", "View from Towards Pandan Gardens"),
    "4712": ("AYE", "View from After Tuas West Road"),
    "4714": ("AYE", "View from Near West Coast Walk"),
    "4716": ("AYE", "View from Entrance from Benoi Rd"),
    "4798": ("Sentosa Gateway", "View from Sentosa Gateway (Towards Telok Blangah)"),
    "4799": ("Sentosa Gateway", "View from Sentosa Gateway (Towards Sentosa)"),
    "5794": ("PIE", "View from Bedok North"),
    "5795": ("PIE", "View from Eunos Flyover"),
    "5797": ("PIE", "View from Paya Lebar Flyover"),
    "5798": ("PIE", "View from Kallang Way"),
    "5799": ("PIE", "View from Woodsville Flyover"),
    "6701": ("PIE", "View from Kim Keat Link"),
    "6703": ("PIE", "View from Thomson Flyover"),
    "6704": ("PIE", "View from Mount Pleasant"),
    "6705": ("PIE", "View from Adam Road"),
    "6706": ("PIE", "View from Bukit Timah Expressway"),
    "6708": ("PIE", "View from Nanyang Flyover"),
    "6710": ("PIE", "View from Entrance from Jalan Anak Bukit"),
    "6711": ("PIE", "View from Entrance to PIE from ECP Changi"),
    "6712": ("PIE", "View from Exit 27 to Clementi Ave 6"),
    "6713": ("PIE", "View from Entrance from Simei Ave"),
    "6714": ("PIE", "View from Exit 35 to KJE"),
    "6715": ("PIE", "View from Hong Kah Flyover"),
    "6716": ("PIE", "View from Tuas Flyover"),
    "7791": ("TPE", "View from Upp Changi Flyover Towards PIE"),
    "7793": ("TPE", "View from Tampines Ave 10 Entrance"),
    "7794": ("TPE", "View from TPE(KPE) Exit"),
    "7795": ("TPE", "View from Entrance To Tampines Flyover"),
    "7796": ("TPE", "View from Exit to Punggol Flyover"),
    "7797": ("TPE", "View from Seletar West Link"),
    "7798": ("TPE", "View from Seletar Flyover"),
    "8701": ("KJE", "View from Choa Chu Kang West Flyover"),
    "8702": ("KJE", "View from Exit To BKE"),
    "8704": ("KJE", "View from Entrance From Choa Chu Kang Dr"),
    "8706": ("KJE", "View from Tengah Flyover"),
    "9701": ("SLE", "View from Lentor Flyover"),
    "9702": ("SLE", "View from Upp Thomson Flyover"),
    "9703": ("SLE", "View from SLE(BKE) Exit"),
    "9704": ("SLE", "View from Ulu Sembawang Flyover"),
    "9705": ("SLE", "View from Marsiling Flyover"),
    "9706": ("SLE", "View from Mandai Flyover"),
}
